### PR TITLE
Update to latest Firebase, redirect directly

### PR DESCRIPTION
**Pull request by filiph**
This is the version currently served by http://angulardart.org.

### CODE REVIEW

**Comment by chalin** [comment]
I'm not sure about the minimal `index.html`, but if it works, then it all LGTM.

**Comment by kwalrath** [comment]
I'm fine with it. It looks like you don't want the utm* stuff for redirects directly from the homepage?

**Comment by filiph** [comment]
@chalin That is there from the previous version and should never be served (per firebase.yml, all requests to everything on angulardart.org will go to webdev.dartlang.org/angular). I assume it was put there as some kind of a safety in case Firebase Hosting doesn't redirect on the server/routing level. I'm okay with deleting it.

@kwalrath The utm_ stuff was there when redirecting through angular.io/dart. The hops looked like this:

    angulardart.org 301 -> angular.io/dart 301 -> webdev.dartlang.org/angular?utm_...&utm_source=angular.io/dart

For consistency in our analytics, I mimicked the `utm_*` parameters and change `utm_source` to `angulardart.org`. Happy to remove that, though.

**Comment by chalin** [comment]
Thanks for the explanation. Either way works for me.

**Comment by filiph** [comment]
FYI: I'll need one of you two land this. I don't have that power over here in angularland :).

**Comment by kwalrath** [comment]
I don't recall this auto-updating. @filiph do you want me to look into how this gets updated?

**Comment by filiph** [comment]
I had to do it manually, in collaboration with the Firebase team. The person who had access to the angulardart-org firebase project had left the team. This is why this took so long and why Naomi's previous change here didn't have any effect.

**Comment by filiph** [comment]
Thanks for merging!

**Pull request merged**
